"""first draft of db

Revision ID: f5d3303466ab
Revises: 
Create Date: 2023-09-18 13:20:25.033016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d3303466ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jav_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jav_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('quality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quality_id'], ['jav_quality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grab_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('javmovie_id', sa.Integer(), nullable=False),
    sa.Column('download_page', sa.String(), nullable=True),
    sa.Column('_download_links', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['javmovie_id'], ['jav_movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grab_history')
    op.drop_table('jav_movie')
    op.drop_table('jav_quality')
    # ### end Alembic commands ###
